---
version: "3"
services:
  rundeck:
    image: rundeck/rundeck:SNAPSHOT
    #    links:
    #          - mysql
    container_name: rundeck
    dns_search: exemplo.com.br
    restart: always
    tty: true
    #    network_mode: "host"
    #    networks:
    #      app_net:
    #        ipv4_address: 172.16.238.10
    #    dns:
    #      - 127.0.0.1
    #      - 8.8.8.8
    ports:
      - 4440:4440
    expose:
      - "80/tcp"
      - "443/tcp"
    extra_hosts:
      - "balancer.dexter.com.br:172.16.238.1"
    volumes:
      - data:/home/rundeck/server/data
    environment:
      RUNDECK_DATABASE_DRIVER: com.mysql.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: rundeck
      RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false

volumes:
  data:
